/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_moscal_FFmpegNative */

#ifndef _Included_com_example_moscal_FFmpegNative
#define _Included_com_example_moscal_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_moscal_FFmpegNative
 * Method:    avcodec_find_decoder
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_moscal_FFmpegNative_avcodec_1find_1decoder
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
